# For some reason, this is needed to make sphinx gallery use the svg files generated by our examples
# See https://sphinx-gallery.github.io/stable/advanced.html#example-3-matplotlib-with-svg-format for more details

from sphinx_gallery.scrapers import matplotlib_scraper


def matplotlib_svg_scraper(*args, **kwargs):
    return matplotlib_scraper(*args, format="svg", **kwargs)
