#!/bin/bash

# This script compares the images generated by the example scripts to a set of reference images

test_passed=true # Kepp track of whether any tests fail

# First check that there aren't any images produced by the examples that don't have a reference image
for f in *.png
do
    if ! test -f "ref/$f"; then
        echo ""
        echo "$f doesn't have a reference image to compare to"
        test_passed=false
    fi
done

mkdir -p diffs

# For each image in the ref directory, check that there is a corresponding image in the current directory and then compare them
for f in ref/*.png
do
    echo ""
    base_name=$(basename ${f})

    if test -f "$base_name"; then
        filename_no_ext="${base_name%.*}"
        echo "Comparing $base_name and $f"
        odiff --antialiasing --threshold=0.1 --diff-mask $base_name $f diffs/${filename_no_ext}-diff.png
        if [ $? -ne 0 ]; then
            test_passed=false
        fi
    else
        echo "Couldn't find image to compare against $f"
        test_passed=false
    fi
done

echo ""
echo "==========================="
if [ "$test_passed" = true ] ; then
    echo "All comparisons passed"
    echo "==========================="
    exit 0
else
    echo "Some comparisons failed"
    echo "==========================="
    exit 0 # In future (if we can make the image comparison more robust) we should exit with a non-zero exit code (e.g. 1)
fi
